import { PHC } from '../types';

export const INITIAL_PHCS: PHC[] = [
  {
    id: 'phc-velachery',
    name: 'PHC Velachery',
    district: 'Chengalpattu',
    state: 'Tamil Nadu',
    lat: 12.9815,
    lng: 80.2180,
    bedsTotal: 24,
    bedsOccupied: 19,
    staffPresent: 8,
    staffTotal: 10,
    contactPhone: '+91 98401 23451',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 420,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 120,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 350,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 85,
        unit: 'bottles',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 110,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 600,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 24).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 45,
        unit: 'vials',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 30,
        unit: 'kits',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-tambaram',
    name: 'PHC Tambaram Urban',
    district: 'Chengalpattu',
    state: 'Tamil Nadu',
    lat: 12.9229,
    lng: 80.1275,
    bedsTotal: 30,
    bedsOccupied: 28,
    staffPresent: 11,
    staffTotal: 12,
    contactPhone: '+91 98401 23452',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 140,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 1).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 80,
        unit: 'kits',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 90,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 40,
        unit: 'bottles',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 65,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 500,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 15,
        unit: 'vials',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 18,
        unit: 'kits',
        reorderThreshold: 90,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-guduvancheri',
    name: 'PHC Guduvancheri',
    district: 'Chengalpattu',
    state: 'Tamil Nadu',
    lat: 12.8452,
    lng: 80.0617,
    bedsTotal: 18,
    bedsOccupied: 10,
    staffPresent: 6,
    staffTotal: 8,
    contactPhone: '+91 98401 23453',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 650,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 480,
        unit: 'kits',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 400,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 16).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 320,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 210,
        unit: 'bottles',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 410,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 20).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 80,
        unit: 'vials',
        reorderThreshold: 35,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 110,
        unit: 'kits',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-chengalpattu-main',
    name: 'PHC Chengalpattu Main',
    district: 'Chengalpattu',
    state: 'Tamil Nadu',
    lat: 12.6819,
    lng: 79.9888,
    bedsTotal: 40,
    bedsOccupied: 31,
    staffPresent: 14,
    staffTotal: 15,
    contactPhone: '+91 98401 23454',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 800,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 650,
        unit: 'kits',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 520,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 450,
        unit: 'bottles',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 340,
        unit: 'bottles',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 920,
        unit: 'strips',
        reorderThreshold: 500,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 140,
        unit: 'vials',
        reorderThreshold: 60,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 180,
        unit: 'kits',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-sriperumbudur',
    name: 'PHC Sriperumbudur',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    lat: 12.9686,
    lng: 79.9443,
    bedsTotal: 20,
    bedsOccupied: 16,
    staffPresent: 7,
    staffTotal: 9,
    contactPhone: '+91 98401 23455',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 210,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 140,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 310,
        unit: 'strips',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 75,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 95,
        unit: 'bottles',
        reorderThreshold: 90,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 380,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 22).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 28,
        unit: 'vials',
        reorderThreshold: 35,
        lastUpdated: new Date(Date.now() - 3600000 * 16).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 40,
        unit: 'kits',
        reorderThreshold: 60,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-kanchipuram-town',
    name: 'PHC Kanchipuram Town',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    lat: 12.8342,
    lng: 79.7036,
    bedsTotal: 35,
    bedsOccupied: 22,
    staffPresent: 12,
    staffTotal: 14,
    contactPhone: '+91 98401 23456',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 720,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 590,
        unit: 'kits',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 490,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 380,
        unit: 'bottles',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 260,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 810,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 19).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 110,
        unit: 'vials',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 13).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 140,
        unit: 'kits',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-walajabad',
    name: 'PHC Walajabad',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    lat: 12.7936,
    lng: 79.8142,
    bedsTotal: 16,
    bedsOccupied: 14,
    staffPresent: 5,
    staffTotal: 6,
    contactPhone: '+91 98401 23457',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 180,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 95,
        unit: 'kits',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 160,
        unit: 'strips',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 13).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 50,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 45,
        unit: 'bottles',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 310,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 21).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 22,
        unit: 'vials',
        reorderThreshold: 30,
        lastUpdated: new Date(Date.now() - 3600000 * 17).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 25,
        unit: 'kits',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-poonamallee',
    name: 'PHC Poonamallee',
    district: 'Thiruvallur',
    state: 'Tamil Nadu',
    lat: 13.0499,
    lng: 80.0917,
    bedsTotal: 22,
    bedsOccupied: 15,
    staffPresent: 8,
    staffTotal: 10,
    contactPhone: '+91 98401 23458',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 510,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 380,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 290,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 220,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 150,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 490,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 65,
        unit: 'vials',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 85,
        unit: 'kits',
        reorderThreshold: 60,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  }
];
