import { PHC } from '../types';

export const INITIAL_PHCS: PHC[] = [
  // --- TAMIL NADU ---
  {
    id: 'phc-guindy',
    name: 'PHC Guindy Urban',
    district: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0067,
    lng: 80.2020,
    bedsTotal: 24,
    bedsOccupied: 19,
    staffPresent: 8,
    staffTotal: 10,
    contactPhone: '+91 98401 23451',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 420,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 120,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 350,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 85,
        unit: 'bottles',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 110,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 600,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 24).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 45,
        unit: 'vials',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 30,
        unit: 'kits',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-peelamedu',
    name: 'PHC Peelamedu',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    lat: 11.0284,
    lng: 77.0007,
    bedsTotal: 18,
    bedsOccupied: 15,
    staffPresent: 6,
    staffTotal: 7,
    contactPhone: '+91 94421 88902',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 140,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 80,
        unit: 'kits',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 210,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 40,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 1).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 65,
        unit: 'bottles',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 410,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 30).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 18,
        unit: 'vials',
        reorderThreshold: 30,
        lastUpdated: new Date(Date.now() - 3600000 * 20).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 15,
        unit: 'kits',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-samayanallur',
    name: 'PHC Samayanallur',
    district: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9833,
    lng: 78.0500,
    bedsTotal: 15,
    bedsOccupied: 8,
    staffPresent: 5,
    staffTotal: 6,
    contactPhone: '+91 94433 11224',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 580,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 340,
        unit: 'kits',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 480,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 210,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 190,
        unit: 'bottles',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 16).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 520,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 36).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 55,
        unit: 'vials',
        reorderThreshold: 25,
        lastUpdated: new Date(Date.now() - 3600000 * 22).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 95,
        unit: 'kits',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-srirangam',
    name: 'PHC Srirangam',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.8624,
    lng: 78.6946,
    bedsTotal: 20,
    bedsOccupied: 12,
    staffPresent: 7,
    staffTotal: 8,
    contactPhone: '+91 94431 77665',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 610,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 410,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 520,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 260,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 220,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 750,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 40).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 60,
        unit: 'vials',
        reorderThreshold: 35,
        lastUpdated: new Date(Date.now() - 3600000 * 25).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 110,
        unit: 'kits',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },

  // --- KERALA ---
  {
    id: 'phc-edappally',
    name: 'PHC Edappally',
    district: 'Ernakulam (Kochi)',
    state: 'Kerala',
    lat: 10.0261,
    lng: 76.3125,
    bedsTotal: 20,
    bedsOccupied: 16,
    staffPresent: 7,
    staffTotal: 8,
    contactPhone: '+91 94470 55432',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 520,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 280,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 410,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 180,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 150,
        unit: 'bottles',
        reorderThreshold: 90,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 680,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 28).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 50,
        unit: 'vials',
        reorderThreshold: 35,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 70,
        unit: 'kits',
        reorderThreshold: 60,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-kowdiar',
    name: 'PHC Kowdiar',
    district: 'Thiruvananthapuram',
    state: 'Kerala',
    lat: 8.5241,
    lng: 76.9567,
    bedsTotal: 25,
    bedsOccupied: 21,
    staffPresent: 9,
    staffTotal: 10,
    contactPhone: '+91 94471 22334',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 650,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 450,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 590,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 290,
        unit: 'bottles',
        reorderThreshold: 150,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 240,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 820,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 32).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 75,
        unit: 'vials',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 19).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 120,
        unit: 'kits',
        reorderThreshold: 70,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },

  // --- KARNATAKA ---
  {
    id: 'phc-jayanagar',
    name: 'PHC Jayanagar',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    lat: 12.9250,
    lng: 77.5938,
    bedsTotal: 30,
    bedsOccupied: 26,
    staffPresent: 11,
    staffTotal: 12,
    contactPhone: '+91 98450 11998',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 780,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 1).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 510,
        unit: 'kits',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 640,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 3).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 320,
        unit: 'bottles',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 270,
        unit: 'bottles',
        reorderThreshold: 120,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 950,
        unit: 'strips',
        reorderThreshold: 450,
        lastUpdated: new Date(Date.now() - 3600000 * 20).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 90,
        unit: 'vials',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 140,
        unit: 'kits',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-kuvempunagar',
    name: 'PHC Kuvempunagar',
    district: 'Mysuru',
    state: 'Karnataka',
    lat: 12.2958,
    lng: 76.6219,
    bedsTotal: 22,
    bedsOccupied: 17,
    staffPresent: 8,
    staffTotal: 9,
    contactPhone: '+91 98452 33445',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 490,
        unit: 'strips',
        reorderThreshold: 280,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 310,
        unit: 'kits',
        reorderThreshold: 180,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 430,
        unit: 'strips',
        reorderThreshold: 220,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 195,
        unit: 'bottles',
        reorderThreshold: 110,
        lastUpdated: new Date(Date.now() - 3600000 * 13).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 165,
        unit: 'bottles',
        reorderThreshold: 85,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 620,
        unit: 'strips',
        reorderThreshold: 320,
        lastUpdated: new Date(Date.now() - 3600000 * 26).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 48,
        unit: 'vials',
        reorderThreshold: 30,
        lastUpdated: new Date(Date.now() - 3600000 * 17).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 85,
        unit: 'kits',
        reorderThreshold: 50,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },

  // --- ANDHRA PRADESH ---
  {
    id: 'phc-mvp-colony',
    name: 'PHC MVP Colony',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.7420,
    lng: 83.3330,
    bedsTotal: 25,
    bedsOccupied: 20,
    staffPresent: 8,
    staffTotal: 10,
    contactPhone: '+91 98480 66778',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 540,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 360,
        unit: 'kits',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 470,
        unit: 'strips',
        reorderThreshold: 250,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 230,
        unit: 'bottles',
        reorderThreshold: 130,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 195,
        unit: 'bottles',
        reorderThreshold: 95,
        lastUpdated: new Date(Date.now() - 3600000 * 14).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 710,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 29).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 62,
        unit: 'vials',
        reorderThreshold: 35,
        lastUpdated: new Date(Date.now() - 3600000 * 21).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 95,
        unit: 'kits',
        reorderThreshold: 60,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-alipiri',
    name: 'PHC Alipiri',
    district: 'Tirupati',
    state: 'Andhra Pradesh',
    lat: 13.6288,
    lng: 79.4192,
    bedsTotal: 20,
    bedsOccupied: 14,
    staffPresent: 7,
    staffTotal: 8,
    contactPhone: '+91 98481 88990',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 460,
        unit: 'strips',
        reorderThreshold: 260,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 290,
        unit: 'kits',
        reorderThreshold: 170,
        lastUpdated: new Date(Date.now() - 3600000 * 12).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 390,
        unit: 'strips',
        reorderThreshold: 210,
        lastUpdated: new Date(Date.now() - 3600000 * 8).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 175,
        unit: 'bottles',
        reorderThreshold: 100,
        lastUpdated: new Date(Date.now() - 3600000 * 15).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 140,
        unit: 'bottles',
        reorderThreshold: 80,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 580,
        unit: 'strips',
        reorderThreshold: 300,
        lastUpdated: new Date(Date.now() - 3600000 * 34).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 42,
        unit: 'vials',
        reorderThreshold: 28,
        lastUpdated: new Date(Date.now() - 3600000 * 23).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 75,
        unit: 'kits',
        reorderThreshold: 45,
        lastUpdated: new Date(Date.now() - 3600000 * 10).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },

  // --- TELANGANA ---
  {
    id: 'phc-charminar',
    name: 'PHC Charminar',
    district: 'Hyderabad',
    state: 'Telangana',
    lat: 17.3616,
    lng: 78.4747,
    bedsTotal: 28,
    bedsOccupied: 24,
    staffPresent: 10,
    staffTotal: 11,
    contactPhone: '+91 98490 22334',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 720,
        unit: 'strips',
        reorderThreshold: 350,
        lastUpdated: new Date(Date.now() - 3600000 * 2).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 480,
        unit: 'kits',
        reorderThreshold: 220,
        lastUpdated: new Date(Date.now() - 3600000 * 7).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 610,
        unit: 'strips',
        reorderThreshold: 280,
        lastUpdated: new Date(Date.now() - 3600000 * 4).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 310,
        unit: 'bottles',
        reorderThreshold: 160,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 250,
        unit: 'bottles',
        reorderThreshold: 110,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 890,
        unit: 'strips',
        reorderThreshold: 400,
        lastUpdated: new Date(Date.now() - 3600000 * 22).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 82,
        unit: 'vials',
        reorderThreshold: 45,
        lastUpdated: new Date(Date.now() - 3600000 * 16).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 130,
        unit: 'kits',
        reorderThreshold: 75,
        lastUpdated: new Date(Date.now() - 3600000 * 5).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  },
  {
    id: 'phc-kazipet',
    name: 'PHC Kazipet',
    district: 'Warangal',
    state: 'Telangana',
    lat: 17.9784,
    lng: 79.5305,
    bedsTotal: 18,
    bedsOccupied: 13,
    staffPresent: 6,
    staffTotal: 7,
    contactPhone: '+91 98491 55667',
    stock: {
      'paracetamol-500': {
        id: 'paracetamol-500',
        medicineName: 'Paracetamol 500mg',
        category: 'Analgesics',
        quantity: 410,
        unit: 'strips',
        reorderThreshold: 240,
        lastUpdated: new Date(Date.now() - 3600000 * 6).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'ors-packets': {
        id: 'ors-packets',
        medicineName: 'Oral Rehydration Salts (ORS)',
        category: 'Rehydration',
        quantity: 260,
        unit: 'kits',
        reorderThreshold: 160,
        lastUpdated: new Date(Date.now() - 3600000 * 13).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'amoxicillin-500': {
        id: 'amoxicillin-500',
        medicineName: 'Amoxicillin 500mg',
        category: 'Antibiotics',
        quantity: 360,
        unit: 'strips',
        reorderThreshold: 200,
        lastUpdated: new Date(Date.now() - 3600000 * 9).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'normal-saline-iv': {
        id: 'normal-saline-iv',
        medicineName: 'Normal Saline (NS) 500ml',
        category: 'IV Fluids',
        quantity: 150,
        unit: 'bottles',
        reorderThreshold: 90,
        lastUpdated: new Date(Date.now() - 3600000 * 16).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'dextrose-5-iv': {
        id: 'dextrose-5-iv',
        medicineName: 'Dextrose 5% 500ml',
        category: 'IV Fluids',
        quantity: 125,
        unit: 'bottles',
        reorderThreshold: 75,
        lastUpdated: new Date(Date.now() - 3600000 * 18).toISOString(),
        lastUpdatedSource: 'photo',
      },
      'metformin-500': {
        id: 'metformin-500',
        medicineName: 'Metformin 500mg',
        category: 'Chronic Care',
        quantity: 530,
        unit: 'strips',
        reorderThreshold: 280,
        lastUpdated: new Date(Date.now() - 3600000 * 35).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'insulin-regular': {
        id: 'insulin-regular',
        medicineName: 'Insulin Regular 100IU/ml',
        category: 'Chronic Care',
        quantity: 38,
        unit: 'vials',
        reorderThreshold: 25,
        lastUpdated: new Date(Date.now() - 3600000 * 24).toISOString(),
        lastUpdatedSource: 'manual',
      },
      'platelet-buffer-kits': {
        id: 'platelet-buffer-kits',
        medicineName: 'Platelet Buffer Kits',
        category: 'Supplies',
        quantity: 65,
        unit: 'kits',
        reorderThreshold: 40,
        lastUpdated: new Date(Date.now() - 3600000 * 11).toISOString(),
        lastUpdatedSource: 'photo',
      }
    }
  }
];
